// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(KaffeshopContext))]
    partial class KaffeshopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Ingredient.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecipeIngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RecipeIngredientsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecipeIngredientsId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Models.MenuItem.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("Models.MenuItem.MenuRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuRecipes");
                });

            modelBuilder.Entity("Models.Recipe.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MenuRecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Seasonal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MenuRecipeId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Models.Recipe.RecipeIngredients", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Seasonal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("Models.Ingredient.Ingredient", b =>
                {
                    b.HasOne("Models.Recipe.RecipeIngredients", null)
                        .WithMany("AddedIngredients")
                        .HasForeignKey("RecipeIngredientsId");
                });

            modelBuilder.Entity("Models.Recipe.Recipe", b =>
                {
                    b.HasOne("Models.MenuItem.MenuRecipe", null)
                        .WithMany("AttachRecipe")
                        .HasForeignKey("MenuRecipeId");
                });

            modelBuilder.Entity("Models.MenuItem.MenuRecipe", b =>
                {
                    b.Navigation("AttachRecipe");
                });

            modelBuilder.Entity("Models.Recipe.RecipeIngredients", b =>
                {
                    b.Navigation("AddedIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
